[package]
name = "skope"
version = "0.5.0"
description = "Accelerated genome containment and abundance estimation"
authors = ["Bede Constantinides <b@bede.im>"]
edition = "2024"
repository = "https://github.com/bede/skope"
homepage = "https://github.com/bede/skope"
keywords = ["bioinformatics", "genomics"]
categories = ["science", "command-line-utilities"]
license = "MIT"
exclude = ["data/*", "plot/*", "*.pdf", "*.png"]

[lints.clippy]
too_many_arguments = "allow"

[features]
# Enable all compression formats supported by niffler. Disable for faster builds.
compression = ["niffler/default", "dep:flate2"]
# Use to still handle .gz files when "compression" is not enabled.
gz = ["niffler/gz", "dep:flate2"]
default = ["compression"]

[lib]
name = "skope"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
rayon = "1"
csv = "1.4"
rapidhash = "4.4.1"
parking_lot = "0.12"
indicatif = "0.18"
wincode = "0.6.1"

packed-seq = "5.0.0"
simd-minimizers = "3.0.0"

paraseq = { version = "0.6.0", default-features = false, features = ["anyhow", "niffler"] }
niffler = { version = "3", default-features = false }

flate2 = { version = "1.1", features = ["zlib-rs"], optional = true }

[dev-dependencies]
tempfile = "3.27"
nix = { version = "0.31", features = ["fs", "term"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = false
debug = false

[profile.dist]
inherits = "release"
